### 0417 예외처리(Exception Handling)

------



#### 에러와 예외

- 어떤 원인에 의해 오동작하거나 비정상적으로 종료되는 경우
- 심각도에 따른 분류

  - Error

    - 메모리 부족, stack overflow와 같이 일단 발생하면 복구할 수 없는 상황
    - 프로그램의 비정상적인 종료를 막을 수 없기 때문에 디버깅이 필요하다. 
  - Exception
  
    - 읽으려는 파일이 없거나, 네트워크의 연결이 안 되는 등 수습될 수 있는 비교적 상태가 약한 것들
    - 프로그램 코드에 의해 수습 가능하다.
  
- 예외처리가 필요한 이유 
  - checked exception에 대응하기 위해
  - unchecked exception이라 할 지라도 예외상황을 전달하기 위해





**:star: try, catch**

```java
// try, catch 구문

try{
    //예외가 발생할 수 있는 코드
} catch(Exception e){
    //예외가 발생할 때 처리할 코드
}

```

- try ~ catch 문에서의 흐름
  - try 블록에서 예외가 발생하면
  - jvm이 해당 Exception 클래스의 객체 생성 후  던짐(throw)
  - 던져진 exception을 처리할 수 있는 catch블록에서 이를 받은 후 처리
  - (적당한 catch 블록을 만나지 못하면 예외처리 실패)
  - 정상적으로 처리되면, try-catch 블록을 벗어나 다음 문장들 진행
  - try에서 예외가 발생하지 않는다면 catch문을 거치지 않는다.

```java
public class simpleException {
	public static void main(String[] args) {
		int[] intArray = {10};
		try{
			System.out.println(intArray[2]);
		}catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("예외 처리 완료!");
			e.printStackTrace();
		}
		System.out.println("프로그램을 종료합니다!");
	}
}
```

```java
import java.util.InputMismatchException;
import java.util.Scanner;

public class Test {
	public static void main(String[] args) {
		doSomething();
	}
	static void doSomething() {
		Scanner sc = new Scanner(System.in);
		try{
			int n = sc.nextInt();
			System.out.println(n);
		}catch (InputMismatchException e) {
			System.out.println("똑바로 좀 입력하시오.");
		}
	}
}

```



- 다중 exception handling
  - try 블록에서 여러 종류의 예오기ㅏ 발생할 경우, 하나의 try 블록에 여러 개의 catch 블록 추가 가능
  - 다중 catch 문장 작성 순서 유의해야 함. 상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 catch블록이 동작할 기회를 잃는다.